lum_create_user:
    pattern:  /create
    defaults: { _controller: LksUserManagementBundle:Default:create }
lum_list_users:
    pattern:  /list
    defaults: { _controller: LksUserManagementBundle:Default:listAndCreate }
