parameters:
    database_driver: pdo_mysql
    database_host: 127.0.0.1
    database_port: 8889
    database_name: capacity
    database_user: test
    database_password: null
    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: null
    mailer_password: null
    locale: en
    secret: 3ba4c70fd4d3b605c79c59ce411f628eb2dd914c
    database_path: null
