lks_project_management:
    resource: "@LksProjectManagementBundle/Resources/config/routing.yml"
    prefix:   /

lks_user_management:
    resource: "@LksUserManagementBundle/Resources/config/routing.yml"
    prefix:   /

