lks_project_management:
    resource: "@LksProjectManagementBundle/Resources/config/routing.yml"
    prefix:   /

lks_member_management:
    resource: "@LksMemberManagementBundle/Resources/config/routing.yml"
    prefix:   /

