parameters:
    lks_capacity_management.capacity.class: Lks\CapacityManagementBundle\Services\CapacityService

services:
    lks_capacity_management.capacity:
        class: %lks_capacity_management.capacity.class%
        arguments: [@memberDao, @projectDao, @logger]
