lmm_create_user:
    pattern:  /create
    defaults: { _controller: LksMemberManagementBundle:Member:create }
lmm_homepage:
    pattern:  /members
    defaults: { _controller: LksMemberManagementBundle:Member:members }

lmm_delete_member:
    pattern:  /members/delete/{memberId}
    defaults: { _controller: LksMemberManagementBundle:Member:delete }
