parameters:
    lks_user_management.member.class: Lks\UserManagementBundle\MemberService

services:
    lks_user_management.member:
        class: %lks_user_management.member.class%
        arguments: [@memberDao]
