parameters:
    lks_project_management.project.class: Lks\ProjectManagementBundle\ProjectService

services:
    lks_project_management.project:
        class: %lks_project_management.project.class%
        arguments: [@projectDao]
